name: Tyler Cipriani
description: Gentleman, Scholar, Web Hacker
url: http://www.tylercipriani.com
auto: true
server: true
markdown: rdiscount
paginate: 5
permalink: /blog/:year/:month/:day/:title/
paginate_path: "/blog/page/:num/"
exclude:
    - Gemfile
    - Gemfile.lock
    - Makefile
    - Gruntfile.js
    - package.json
    - sass
    - node_modules
    - dev
    - gallery.html
    - components
    - styles/main.css
    - styles/gallery.css
    - README.md

gems:
    - jemoji
    - jekyll-sitemap
