name: Tyler Cipriani
description: Gentleman, Scholar, Web Hacker
url: http://www.tylercipriani.com
auto: true
server: true
markdown: rdiscount
exclude: Gruntfile.js, package.json, sass, node_modules, dev, gallery.html, components, styles/main.css, styles/gallery.css
